//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lý_Bán_vé_Máy_bay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chuyến_bay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chuyến_bay()
        {
            this.Vé = new HashSet<Vé>();
        }
    
        public string Mã_chuyến_bay { get; set; }
        public string Loại_máy_bay { get; set; }
        public int Số_lượng_chỗ_ngồi { get; set; }
        public System.TimeSpan Giờ_khởi_hành { get; set; }
        public System.DateTime Ngày_khởi_hành { get; set; }
        public string Mã_sân_bay_đi { get; set; }
        public string Mã_sân_bay_đến { get; set; }
    
        public virtual Sân_bay Sân_bay { get; set; }
        public virtual Sân_bay Sân_bay1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vé> Vé { get; set; }
    }
}
