//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lý_Bán_vé_Máy_bay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dịch_vụ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dịch_vụ()
        {
            this.Loại_vé = new HashSet<Loại_vé>();
        }
    
        public string Mã_dịch_vụ { get; set; }
        public string Tên_dịch_vụ { get; set; }
        public int Trị_giá_thức_ăn { get; set; }
        public int Trị_giá_thức_uống { get; set; }
        public int Trị_giá_dịch_vụ_khác { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loại_vé> Loại_vé { get; set; }
    }
}
