//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lý_Bán_vé_Máy_bay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loại_vé
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loại_vé()
        {
            this.Vé = new HashSet<Vé>();
        }
    
        public string Mã_loại_vé { get; set; }
        public string Tên_loại_vé { get; set; }
        public int Giá_tiền { get; set; }
        public string Mã_dịch_vụ { get; set; }
    
        public virtual Dịch_vụ Dịch_vụ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vé> Vé { get; set; }
    }
}
