//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lý_Bán_vé_Máy_bay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyVeMayBayEntities : DbContext
    {
        public QuanLyVeMayBayEntities()
            : base("name=QuanLyVeMayBayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chuyến_bay> Chuyến_bay { get; set; }
        public virtual DbSet<Dịch_vụ> Dịch_vụ { get; set; }
        public virtual DbSet<Khách> Khách { get; set; }
        public virtual DbSet<Loại_vé> Loại_vé { get; set; }
        public virtual DbSet<Sân_bay> Sân_bay { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Vé> Vé { get; set; }
    }
}
