//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lý_Bán_vé_Máy_bay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sân_bay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sân_bay()
        {
            this.Chuyến_bay = new HashSet<Chuyến_bay>();
            this.Chuyến_bay1 = new HashSet<Chuyến_bay>();
        }
    
        public string Mã_sân_bay { get; set; }
        public string Tên_sân_bay { get; set; }
        public string Tỉnh_Thành_phố { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chuyến_bay> Chuyến_bay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chuyến_bay> Chuyến_bay1 { get; set; }
    }
}
