//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lý_Bán_vé_Máy_bay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tài_khoản
    {
        public string email { get; set; }
        public string password { get; set; }
    }
}
