//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lý_Bán_vé_Máy_bay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vé
    {
        public string Số_vé { get; set; }
        public System.DateTime Ngày_đặt_vé { get; set; }
        public System.DateTime Ngày_nhận_vé { get; set; }
        public string Mã_chuyến_bay { get; set; }
        public string Mã_loại_vé { get; set; }
        public string Mã_khách { get; set; }
    
        public virtual Chuyến_bay Chuyến_bay { get; set; }
        public virtual Khách Khách { get; set; }
        public virtual Loại_vé Loại_vé { get; set; }
    }
}
